<a href="https://colab.research.google.com/github/13DMAA/DSM20/blob/master/Lesson_1_numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тема “Вычисления с помощью Numpy”

## Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [1]:
import numpy as np
a = np.array([1, 2, 3, 3, 1, 6, 8, 11, 10, 7])
a.shape = (2, 5)
a = a.transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [2]:
mean_a = [a[:,0].mean(),a[:,1].mean()]
mean_a

[2.0, 8.4]

## Задание 2


Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [3]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [4]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
a_centered_sp

8.0

In [5]:
a_centered_sp = a_centered.transpose()[0] @ a_centered.transpose()[1]
a_centered_sp 

8.0

In [6]:
a_centered_sp = a_centered[:,0].dot(a_centered.transpose()[1])
a_centered_sp

8.0

In [7]:
a_centered_sp/(a.shape[0]-1)

2.0

## Задание 4*

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
Выборочная ковариация и выборочная дисперсия — Студопедия
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [8]:
np.cov(a.transpose())[0,1]

2.0

## Задание 5**

Необходимо реализовать метод сортировки целых (int) элементов. Метод должен быть реализован без использования “готовых” методов ( sorted, np.sort() ).


In [9]:
int_array = np.array([1, 5, 6, 4, -4, 1, 52, 11, 0, 8])
def sort_(array_, reverse = False):
  sorted_array = np.array([], dtype=np.int)
  while len(array_):
    if reverse:
      sorted_array = np.append(sorted_array,array_[array_==array_.max()],axis=0)
      # print(sorted_array)
      array_ = array_[array_<array_.max()]
    else:
      sorted_array = np.append(sorted_array,array_[array_==array_.min()],axis=0)
      # print(sorted_array)
      array_ = array_[array_>array_.min()]
  return sorted_array
print(sort_(int_array,True))
print(sort_(int_array))
print(int_array)

[52 11  8  6  5  4  1  1  0 -4]
[-4  0  1  1  4  5  6  8 11 52]
[ 1  5  6  4 -4  1 52 11  0  8]


# Тема “Работа с данными в Pandas”

## Задание 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [10]:
import pandas as pd
authors = pd.DataFrame({
    'author_id':[1,2,3],
    'author_name':['Тургенев', 'Чехов', 'Островский']
})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [11]:
books = pd.DataFrame()
author_id = [1, 1, 1, 2, 2, 3, 3]
book_title =  ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']
b_t = pd.Series(book_title)
price = [450, 300, 350, 500, 450, 370, 290]
books['author_id'] = author_id
books['book_title'] = b_t
books['price'] = price
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.


In [12]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [13]:
top5 = authors_price.sort_values(by = 'price', ascending = False).reset_index(drop = True).head(5)
top5


author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

In [14]:
top5 = authors_price.nlargest(5, 'price')
top5.reset_index(drop = True, inplace = True)
top5

author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

## Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [15]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [16]:
authors_stat = pd.DataFrame()
authors_stat['author_name'] = authors_price['author_name'].unique()
# authors_stat['author_name'] = authors_price.groupby(by = 'author_name')['author_name']
authors_stat['min_price'] = authors_price.groupby(by = 'author_name').min()['price'].reset_index(drop = True) #Фухх, налепил конструкцию
# вроде всё логично, но громозко - я "сортирую и соединяю" по имени автора исходный датафрейм, далее в "соединенных значениях" высчитывается минимумы
# но минимумы берутся по всем столбцам, я беру только столбец 'price', но в нем остаются индексы, которые пол дня мешали мне и выдавали NaN,
# я их удаляю и вставляю
authors_stat['max_price'] = authors_price.groupby(by = 'author_name').max()['price'].reset_index(drop = True)
authors_stat['mean_price'] = authors_price.groupby(by = 'author_name').mean()['price'].reset_index(drop = True).astype('int32')
authors_stat

author_name  min_price  max_price  mean_price
0    Тургенев        290        370         330
1       Чехов        300        450         366
2  Островский        450        500         475

## Задание 5*

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].


In [17]:
authors_price['cover'] =  ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.


In [18]:
?pd.pivot_table

In [19]:
book_info = pd.pivot_table(authors_price, index = 'author_name', columns = 'cover', values = 'price', aggfunc = np.sum, fill_value = 0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [20]:
book_info.to_pickle('book_info.pkl')

In [21]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [22]:
book_info.equals(book_info2)

True

## Задание 5**

Вычисление метрик для мониторинга.
суммарная выручка
кол-во покупок
средний чек
среднее кол-во товаров в покупке
Дополнительно добавим возможность фильтровать данные по различным параметрам. Это может быть полезно чтобы посмотреть как меняются продажи в двух группах, или в какой-то отдельной категории товаров.
На вход функции будет подаваться датафрейм с данными о продажах, словарь с фильтрами и период, за который нужно посчитать метрики.
Функция должна вернуть датафрейм, в индексах которого будут все даты из указанного периода отсортированные по возрастанию, а столбцы - метрики ['revenue', 'number_purchases', 'average_check', 'average_number_items']. Формат данных столбцов - float, формат данных индекса - datetime64[ns].
Если в какие-то дни не было продаж, то нужно заполнить пропуск нулём.
